# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=16)),
                ('g_boy_num', models.IntegerField(default=30)),
                ('g_girl_num', models.IntegerField(default=20)),
            ],
        ),
    ]
