# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_grade'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='grade',
            managers=[
                ('g_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
