# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-11 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_teacher_t_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='t_hobby',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
