# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.Person'),
        ),
    ]
