# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='App.Person'),
        ),
    ]
